// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcti1Fv4I7av9tFrsTe8r_bnZBHVHI3mA',
    appId: '1:292477352967:web:63055c8f8e0aace38c3ea2',
    messagingSenderId: '292477352967',
    projectId: 'authflutter-d0201',
    authDomain: 'authflutter-d0201.firebaseapp.com',
    storageBucket: 'authflutter-d0201.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0rPqfr0Q2mb0hK8L5p-HpZ8SxW29A-qk',
    appId: '1:292477352967:android:242d402593bb37a08c3ea2',
    messagingSenderId: '292477352967',
    projectId: 'authflutter-d0201',
    storageBucket: 'authflutter-d0201.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCar-3jL6iB8TSGSkKKZqJV4jMzu06BKc',
    appId: '1:292477352967:ios:1c88b2602b817dab8c3ea2',
    messagingSenderId: '292477352967',
    projectId: 'authflutter-d0201',
    storageBucket: 'authflutter-d0201.appspot.com',
    iosBundleId: 'com.example.authAppWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCar-3jL6iB8TSGSkKKZqJV4jMzu06BKc',
    appId: '1:292477352967:ios:ec9f348fbbd821b98c3ea2',
    messagingSenderId: '292477352967',
    projectId: 'authflutter-d0201',
    storageBucket: 'authflutter-d0201.appspot.com',
    iosBundleId: 'com.example.authAppWithFirebase.RunnerTests',
  );
}
